export const UPSERT_COURSE = 'usr/upsertCourse'
export const LIST_COURSE = 'usr/listCourse'
export const LOAD_COURSE = 'usr/loadCourse'
export const UPSERT_CHAPTER = 'usr/upsertChapter'
export const LIST_CHAPTER = 'usr/listChapter'
export const MOVE_CHAPTER = 'usr/moveChapter'
export const LOAD_CHAPTER = 'usr/loadChapter'
export const UPSERT_CLASS = 'usr/upsertClass'
export const LIST_CLASS = 'usr/listClass'
export const UPSERT_TEACH_RECORD = 'usr/upsertTeachRecord'
export const LIST_TEACH_RECORD = 'usr/listTeachRecord'
export const LIST_CLASS_USER = 'usr/listClassUser'
export const UPSERT_CLASS_USER = 'usr/upsertClassUser'

export const UPLOAD_FILE = 'usr/upload'
